name: flutter_clean_architecture
description: Flutter with clean architecture application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^2.0.1

  # Service Locator
  get_it: ^3.0.3

  # Value Equality
  equatable: ^1.0.1

  # Functional Programming Thingies
  dartz: ^0.8.8

  # Remote API
  data_connection_checker: ^0.3.4
  chopper: ^3.0.1+1

  # Local Cache
  shared_preferences: ^0.5.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: 0.39.14

  build_runner: 1.10.0
  chopper_generator: ^3.0.1+1

  mockito: ^4.1.1

flutter:
  uses-material-design: true
